apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-config
  namespace: monitoring
data:
  config.yml: |
    modules:
      http_2xx:
        prober: http
        timeout: 10s
        http:
          valid_status_codes: [200]
          method: GET
          preferred_ip_protocol: "ip4"
          no_follow_redirects: false
