apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  namespace: mvp-deploy-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
        - name: auth-api
          image: drpaul1864/mvp-deploy:auth-api-1.0.0
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: auth-api-env-file
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
      restartPolicy: Always
