apiVersion: v1
kind: Service
metadata:
  name: auth-api
  namespace: mvp-deploy-app
spec:
  type: ClusterIP
  selector:
    app: auth-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
