apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: mvp-deploy-app
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31808
