apiVersion: v1
kind: Service
metadata:
  name: ui-api
  namespace: mvp-deploy-app
spec:
  type: ClusterIP
  selector:
    app: ui-api
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
