pipeline {
    agent {
        node {
            label 'agent-1'
        }
    }
    
    environment {
        DOCKER_REGISTRY = 'drpaul1864/mvp-deploy'
        DOCKER_HUB_USER = 'drpaul1864'
        K8S_NAMESPACE = 'mvp-deploy-app'
        BUILD_TAG = "${new Date().format('yyyyMMdd_HHmm')}"
    }
    
    stages { 
        stage('Checkout git') {
            steps {
                sh "echo 'Выбрана ветка: ${params.BRANCH_NAME}'"
                git branch: "${params.BRANCH_NAME}", url: 'git@github.com:drahunpavel/mvp-deploy.git'
            }
        }
        stage('Check kubectl') {
            steps {
                sh '''
                    which kubectl
                    kubectl version --client
                '''
            }
        }
        stage('Prepare k8s') {
            steps {
                withCredentials([
                    file(credentialsId: 'kubeconfig-template', variable: 'KUBE_TEMPLATE'),
                    string(credentialsId: 'K8S_TOKEN', variable: 'K8S_TOKEN'),  
                    string(credentialsId: 'K8S_CA_CERT', variable: 'K8S_CA_CERT')
                ]) {
                    // sh 'echo "$K8S_TOKEN" | head -c 50' 
                    // sh 'echo "$K8S_CA_CERT" | head -c 50' 
                    sh '''
                        mkdir -p .kube
                        envsubst < $KUBE_TEMPLATE > .kube/config
                    '''
                }
            }
        }
        stage('Test k8s Connection') {
            steps {
                    // kubectl cluster-info
                    // kubectl get nodes
                sh '''
                    export KUBECONFIG=$(pwd)/.kube/config
                    kubectl --insecure-skip-tls-verify=true cluster-info
                    kubectl --insecure-skip-tls-verify=true get nodes
                '''
            }
        }
        stage('Inject .envs') {
            steps {
                withCredentials([
                    file(credentialsId: 'env-auth-api', variable: 'AUTH_ENV'),
                    file(credentialsId: 'env-ui-api', variable: 'UI_ENV'),
                    file(credentialsId: 'env-db', variable: 'DB_ENV')
                ]) {
                    sh '''
                        rm -f backend/auth-api/.env
                        cp "$AUTH_ENV" backend/auth-api/.env
                        
                        rm -f backend/ui-api/.env
                        cp "$UI_ENV" backend/ui-api/.env
                        
                        rm -f .env
                        cp "$DB_ENV" .env
                        chmod u+w .env
                        echo "" >> .env
                        echo "BUILD_TAG=$BUILD_TAG" >> .env
                    '''
                }
            }
            // steps {
            //     echo "BUILD_TAG: ${env.BUILD_TAG}"
            //     sh 'echo "BUILD_TAG: $BUILD_TAG"'
            //     sh 'docker compose -f docker-compose.jenkins.yml build'
            //     script {
            //         docker.build("${DOCKER_REGISTRY}/auth-api:${env.BUILD_NUMBER}", "./backend/auth-api")
            //         docker.build("${DOCKER_REGISTRY}/ui-api:${env.BUILD_NUMBER}", "./backend/ui-api")
            //         docker.build("${DOCKER_REGISTRY}/frontend:${env.BUILD_NUMBER}", "./frontend")
            //     }
            // }
        }
        stage('Build Images') {
            steps {
                echo "Delete images"
                sh 'docker image prune -a --force'
                
                echo "Build images"
                sh 'docker compose -f docker-compose.jenkins.yml build'
            }
        }
        stage('Push Images') {
            steps {
                
                sh '''
                    echo "docker images:"
                    docker images || echo "failed"
                '''
                
                withCredentials([usernamePassword(credentialsId: 'docker-hub-user-password', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
        
                        docker push ${DOCKER_REGISTRY}:auth-api-${BUILD_TAG}
                        docker push ${DOCKER_REGISTRY}:ui-api-${BUILD_TAG}
                        docker push ${DOCKER_REGISTRY}:frontend-${BUILD_TAG}
                        
                        docker logout
                    '''
                }
            }
        }
    }
}