apiVersion: v1
kind: Config
clusters:
  - name: jenkins-cluster
    cluster:
      server: https://${K8S_API_IP}:6443
      certificate-authority-data: ${K8S_CA_CERT}
contexts:
  - name: jenkins-context
    context:
      cluster: jenkins-cluster
      user: jenkins-user
users:
  - name: jenkins-user
    user:
      token: ${K8S_TOKEN}
current-context: jenkins-context
